Repository nsxiv/nsxiv, pull requests merged in 2021-09, with the labels that each got.

#12 Added ICCCM WM_HINTS
  window.c
Labels: bug

#3 Fix in tabbed with alpha patch
  image.c
  window.c
Labels: bug

#2 Implement fill scale mode
  config.def.h
  image.c
  options.c
  sxiv.1
  sxiv.h
Labels: enhancement

#14 Fix documentation
  sxiv.1
Labels: documentation

#13 Set the _NET_WM_PID and WM_CLIENT_MACHINE X properties
  sxiv.h
  window.c
Labels: enhancement

#10 Custom bar colors
  image.c
  sxiv.1
  sxiv.h
  thumbs.c
  window.c
Labels: enhancement

#40 Add an editorconfig file, closes #25
  .editorconfig
Labels: Workflow

#19 Rework the build system
  .gitignore
  Makefile
  README.md
  image.c
Labels: enhancement, Workflow

#51 add .mark.foreground to Xresources
  CHANGELOG.md
  nsxiv.1
  nsxiv.h
  thumbs.c
  window.c
Labels: enhancement

#64 Fix links in changelog and readme
  CHANGELOG.md
  README.md
Labels: documentation

#68 add -0 for outputting null-terminated list
  commands.c
  nsxiv.h
  options.c
Labels: enhancement

#84 better document what the optional deps do
  README.md
Labels: documentation

#91 fix: unable to use XK_Escape in keybindings
  config.def.h
  main.c
Labels: bug, enhancement

#89 Clarify comment in example key-handler
  examples/key-handler
Labels: documentation

#75 fix: crashing on bad exif thumbnail
  thumbs.c
Labels: bug

#105 update outdated comment in config.def.h
  config.def.h
Labels: documentation
