Repository nsxiv/nsxiv, pull requests merged in 2021-12, with the labels that each got.

#182 fix: compile error
  image.c
Labels: bug

#186 Cleanup manpage
  nsxiv.1
Labels: documentation

#195 add github actions
  .github/workflows/build.yml
Labels: Workflow

#194 fix: broken compilation when using HAVE_LIBFONTS=0
  config.def.h
Labels: bug
