Repository nsxiv/nsxiv, pull requests merged in 2021-11, with the labels that each got.

#154 add links to labels in CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation

#155 make width of navigation area configurable
  commands.c
  config.def.h
  main.c
Labels: enhancement

#164 Apply -0 to stdin and update key-handler doc
  examples/key-handler
  main.c
  nsxiv.1
Labels: don't squash

#150 allow configuring allowed_modifiers in config.h
  config.def.h
  main.c
Labels: bug

#165 Revert "fix: out-of-bounds access when bg not in color map"
  image.c
Labels: bug, don't squash

#175 Reference customization in readme
  README.md
Labels: documentation, extra
