Repository nsxiv/nsxiv, pull requests merged in 2022-01, with the labels that each got.

#184 Calculate imlib2 cache size at runtime based on RAM size
  config.def.h
  image.c
Labels: enhancement

#188 fix: exif orientation on Imlib2 v1.7.5 with jpeg
  image.c
Labels: bug

#200 fix: animation slowdown when zoomed in
  main.c
Labels: bug

#191 fix: reset statusbar after failed keyhandler
  main.c
Labels: bug

#202 Document development workflow for maintainers
  CONTRIBUTING.md
Labels: documentation

#167 make thumbnail bindings configureable
  commands.c
  commands.h
  config.def.h
  main.c
Labels: enhancement
